apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-worker
  namespace: voting
  annotations:
    iam.gke.io/gcp-service-account: "voting-worker@my-gcp-project.iam.gserviceaccount.com"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-vote
  namespace: voting
  annotations:
    iam.gke.io/gcp-service-account: "voting-vote@my-gcp-project.iam.gserviceaccount.com"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-eligibility
  namespace: voting
  annotations:
    iam.gke.io/gcp-service-account: "voting-eligibility@my-gcp-project.iam.gserviceaccount.com"
