apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: voting

resources:
  - ../../base

patches:
  - path: patches/ingress-patch.yaml
  - path: patches/storageclass-patch.yaml
  - path: patches/sa-patch.yaml

images:
  - name: student-voting/eligibility-api
    newName: gcr.io/my-gcp-project/student-voting/eligibility-api
    newTag: v1.0.0
  - name: student-voting/vote-api
    newName: gcr.io/my-gcp-project/student-voting/vote-api
    newTag: v1.0.0
  - name: student-voting/worker
    newName: gcr.io/my-gcp-project/student-voting/worker
    newTag: v1.0.0
  - name: student-voting/results-api
    newName: gcr.io/my-gcp-project/student-voting/results-api
    newTag: v1.0.0
  - name: student-voting/frontend
    newName: gcr.io/my-gcp-project/student-voting/frontend
    newTag: v1.0.0
  - name: student-voting/reveal-gate
    newName: gcr.io/my-gcp-project/student-voting/reveal-gate
    newTag: v1.0.0
