apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-eligibility
  namespace: voting
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-vote
  namespace: voting
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-worker
  namespace: voting
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-results
  namespace: voting
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-frontend
  namespace: voting
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-reveal-gate
  namespace: voting
